# desktop/default.nix — X11/VNC desktop environment
# Nix equivalents of the base-gui apt packages, for stages that need GUI
# support (e.g., ultimate) without inheriting from the apt-based base-gui stage.
#
# Apt → nix mapping:
#   fluxbox                    → xsession.windowManager.fluxbox (HM module)
#   x11vnc                     → pkgs.x11vnc
#   xvfb                       → pkgs.xorg.xorgserver  (provides Xvfb binary)
#   x11-apps                   → pkgs.xorg.xrandr (+ xorg.xset etc.)
#   libx11-6                   → pkgs.xorg.libX11
#   libxcursor-dev             → pkgs.xorg.libXcursor
#   libxkbfile-dev             → pkgs.xorg.libxkbfile
#   libxrandr-dev              → pkgs.xorg.libXrandr
#   libcairo2 / libcairo2-dev  → pkgs.cairo
#   libfontconfig1-dev         → pkgs.fontconfig
#   libfreetype6-dev           → pkgs.freetype
#   libegl1-mesa-dev / libgl1-mesa-dev → pkgs.libGL (mesa)
#   libglew2.2                 → pkgs.glew
#   libglu1-mesa / -dev        → pkgs.libGLU
#   libtiff5-dev               → pkgs.libtiff
#   libwxgtk3.2-1, libwxgtk-webview3.2-1 → pkgs.wxGTK32 (pname="wxwidgets" 3.2.x)
{pkgs, lib, config, ...}:
let
  # Import theme — palette (c), fonts (f), and generated fluxbox cfg.
  theme = import ./themes/main/theme.nix { inherit lib pkgs; };
  inherit (theme) c f cfg init xresources wallpaper pixmaps;

  # UA architecture — must match what Chromium puts in navigator.userAgent.
  # Chrome's "UA reduction" always reports "x86_64" regardless of real CPU,
  # but getHighEntropyValues().architecture leaks the real arch ("arm" on aarch64).
  # Detection scripts compare these and flag the mismatch.
  # Always "x86" because that's what Chrome's UA string claims.
  uaArch = "x86";

  # Static LD_LIBRARY_PATH fallback for the patchright-mcp-cell wrapper.
  # This wrapper is a nix derivation baked at eval time — can't source files at runtime.
  # All other contexts (entrypoint services, interactive shells) use the full-closure
  # /opt/devcell/.nix-ld-library-path generated by home.activation.generateNixLdPath.
  runtimeLibs = with pkgs; [
    glib
    nspr
    nss
    atk
    at-spi2-atk
    dbus
    cups
    libxkbcommon
    at-spi2-core
    xorg.libX11       # libX11 + libX11-xcb — core X11 client lib (Electron SIGTRAP without it)
    xorg.libXcomposite
    xorg.libXcursor
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXi
    xorg.libXrandr
    xorg.libXtst
    xorg.libxkbfile
    libgbm        # GBM buffer manager — mesa itself does NOT provide libgbm.so
    mesa          # Mesa 3D — llvmpipe software rasterizer
    cairo
    pango
    alsa-lib
    pulseaudio    # PulseAudio client lib
    gcc.cc.lib    # libgomp (OpenMP runtime)
    gtk3          # GTK 3 — needed by Electron/Chromium-based GUI apps
  ];
  runtimeLibPath = pkgs.lib.makeLibraryPath runtimeLibs;

  # Patchright MCP config — Chromium launch args for X11 display.
  # No --ozone-platform needed (auto-detects X11 from DISPLAY).
  # WebGL via Mesa Lavapipe: ANGLE → Vulkan → lvp (CPU software renderer).
  # --ignore-gpu-blocklist prevents Chromium from disabling WebGL on software renderers.
  patchrightConfig = pkgs.writeTextFile {
    name = "patchright-mcp-config.json";
    text = builtins.toJSON {
      browser.launchOptions.args = [
        "--use-gl=angle"
        "--use-angle=vulkan"
        "--ignore-gpu-blocklist"
        "--window-size=1920,1040"
        "--force-device-scale-factor=1"
        "--disable-features=AudioServiceSandbox"
        "--autoplay-policy=no-user-gesture-required"
        "--disable-blink-features=AutomationControlled"
      ];
      # Block ServiceWorkers — they run in a separate scope unreachable by init-script.
      # Forces detection scripts to fall back to SharedWorker, which we CAN intercept.
      browser.contextOptions.serviceWorkers = "block";
    };
  };

  # Stealth init-script — injected via --init-script to spoof JS-level fingerprints.
  # Patchright handles CDP layer (Runtime.enable, launch flags);
  # this script handles what page JS can detect.
  stealthInitScript = pkgs.writeTextFile {
    name = "stealth-init.js";
    text = ''
      // Patch navigator.webdriver on the PROTOTYPE (instance-level patch doesn't stick
      // because Chromium defines it on Navigator.prototype, not the instance)
      Object.defineProperty(Navigator.prototype, 'webdriver', {
        get: () => undefined,
        configurable: true
      });

      // Mock chrome.runtime
      window.chrome = {
        runtime: { connect: function(){}, sendMessage: function(){} },
        loadTimes: function() { return {}; },
        csi: function() { return {}; }
      };

      // --- Fix toString leaks (must be early — WebGL patching uses _nativeFnNames) ---
      const origToString = Function.prototype.toString;
      const _nativeFnNames = new WeakMap();
      Function.prototype.toString = function() {
        const name = _nativeFnNames.get(this);
        if (name !== undefined) return 'function ' + name + '() { [native code] }';
        return origToString.call(this);
      };
      _nativeFnNames.set(Function.prototype.toString, 'toString');
      // Register webdriver getter
      const wdDesc = Object.getOwnPropertyDescriptor(Navigator.prototype, 'webdriver');
      if (wdDesc && wdDesc.get) _nativeFnNames.set(wdDesc.get, 'get webdriver');
      // Register chrome.runtime functions
      if (window.chrome && window.chrome.runtime) {
        if (window.chrome.runtime.connect) _nativeFnNames.set(window.chrome.runtime.connect, 'connect');
        if (window.chrome.runtime.sendMessage) _nativeFnNames.set(window.chrome.runtime.sendMessage, 'sendMessage');
        if (window.chrome.loadTimes) _nativeFnNames.set(window.chrome.loadTimes, 'loadTimes');
        if (window.chrome.csi) _nativeFnNames.set(window.chrome.csi, 'csi');
      }

      // Fix plugins + mimeTypes — headless Chrome may have empty arrays.
      if (navigator.plugins.length === 0) {
        const pdfMime = { type: 'application/pdf', suffixes: 'pdf', description: 'Portable Document Format' };
        const fakePlugins = [
          { name: 'Chrome PDF Plugin', filename: 'internal-pdf-viewer', description: 'Portable Document Format', length: 1, 0: pdfMime },
          { name: 'Chrome PDF Viewer', filename: 'mhjfbmdgcfjbbpaeojofohoefgiehjai', description: ' ', length: 1, 0: pdfMime },
          { name: 'Native Client', filename: 'internal-nacl-plugin', description: ' ', length: 1, 0: pdfMime }
        ];
        Object.setPrototypeOf(fakePlugins, PluginArray.prototype);
        Object.defineProperty(navigator, 'plugins', { get: () => fakePlugins });
      }
      if (navigator.mimeTypes.length === 0) {
        const fakeMimes = [
          { type: 'application/pdf', suffixes: 'pdf', description: 'Portable Document Format', enabledPlugin: navigator.plugins[0] }
        ];
        Object.setPrototypeOf(fakeMimes, MimeTypeArray.prototype);
        Object.defineProperty(navigator, 'mimeTypes', { get: () => fakeMimes });
      }
      // Spoof pdfViewerEnabled (headless=new has false)
      Object.defineProperty(navigator, 'pdfViewerEnabled', { get: () => true, configurable: true });

      // Mock languages
      Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en'] });

      // Patch permissions
      const origQuery = window.navigator.permissions.query;
      window.navigator.permissions.query = (params) =>
        params.name === 'notifications'
          ? Promise.resolve({ state: Notification.permission })
          : origQuery(params);

      // Spoof userAgentData high-entropy values — Chromium's userAgent says "x86_64"
      // (UA reduction) but getHighEntropyValues() leaks the real arch on arm64.
      // Detection scripts compare these and flag the mismatch.
      // Architecture value injected at nix build time: "${uaArch}"
      // Must use Object.defineProperty on prototype — direct assignment is a no-op
      // because the property is non-writable on NavigatorUAData.prototype.
      if (typeof NavigatorUAData !== 'undefined') {
        const origGetHigh = NavigatorUAData.prototype.getHighEntropyValues;
        Object.defineProperty(NavigatorUAData.prototype, 'getHighEntropyValues', {
          value: async function(hints) {
            const values = await origGetHigh.call(this, hints);
            values.architecture = '${uaArch}';
            return values;
          },
          writable: true,
          configurable: true
        });
      }

      // --- Web Share API stubs (noWebShare signal) ---
      if (!navigator.share) {
        navigator.share = function(data) {
          return Promise.reject(new DOMException('Share canceled', 'AbortError'));
        };
      }
      if (!navigator.canShare) {
        navigator.canShare = function(data) { return true; };
      }

      // --- Media devices mock (headless has 0 devices → bot signal) ---
      if (navigator.mediaDevices) {
        const _origEnum = navigator.mediaDevices.enumerateDevices;
        navigator.mediaDevices.enumerateDevices = async function() {
          const real = await _origEnum.call(this);
          if (real.length > 0) return real;
          return [
            { deviceId: 'default', kind: 'audioinput', label: "", groupId: 'default' },
            { deviceId: 'communications', kind: 'audiooutput', label: "", groupId: 'default' },
            { deviceId: 'default', kind: 'videoinput', label: "", groupId: 'camera1' }
          ];
        };
      }

      // Spoof WebGL renderer + parameters (hide SwiftShader fingerprint)
      // Use Object.defineProperty on WebGL prototypes — works on ALL contexts
      // regardless of how they're created (Canvas, OffscreenCanvas, iframe).
      // Proxy-wrapping getContext gets bypassed by CreepJS; prototype patching doesn't.
      const _wglVendor = 'Intel Inc.';
      const _wglRenderer = 'Intel Iris OpenGL Engine';
      // Intel-realistic parameter overrides (SwiftShader defaults in comments)
      const _wglParams = {
        37445: _wglVendor,   // UNMASKED_VENDOR_WEBGL
        37446: _wglRenderer, // UNMASKED_RENDERER_WEBGL
        3379:  16384,        // MAX_TEXTURE_SIZE (SwiftShader: 8192)
        3386:  'viewport',   // MAX_VIEWPORT_DIMS — special handling below
        34076: 16384,        // MAX_CUBE_MAP_TEXTURE_SIZE (SwiftShader: 8192)
        34024: 16384,        // MAX_RENDERBUFFER_SIZE (SwiftShader: 8192)
        34047: 16,           // MAX_TEXTURE_MAX_ANISOTROPY_EXT
        36349: 1024,         // MAX_FRAGMENT_UNIFORM_VECTORS (SwiftShader: 221)
        36347: 1024,         // MAX_VERTEX_UNIFORM_VECTORS (SwiftShader: 256)
        36348: 30,           // MAX_VARYING_VECTORS (SwiftShader: 15)
        36183: 8,            // MAX_SAMPLES (SwiftShader: 4)
        7936:  'WebKit',     // VENDOR
        7937:  'WebKit WebGL', // RENDERER
        7938:  'WebGL 1.0 (OpenGL ES 2.0 Chromium)', // VERSION
        35724: 'WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)', // SHADING_LANGUAGE_VERSION
      };
      const _wgl2Extras = {
        7938:  'WebGL 2.0 (OpenGL ES 3.0 Chromium)',
        35724: 'WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)',
        32883: 2048, 33000: 1048576, 33001: 1048576, 34852: 8,
        35657: 4096, 35658: 4096, 35071: 2048, 35077: 7,
        35659: 120, 35968: 4, 35978: 120, 35979: 4, 36063: 8,
        35371: 12, 35373: 12, 35374: 24, 35375: 24, 35376: 65536,
      };
      const _extraExts = ['EXT_texture_filter_anisotropic', 'WEBGL_compressed_texture_s3tc', 'WEBGL_compressed_texture_s3tc_srgb'];

      // Patch getParameter on WebGL prototypes directly
      function _patchWebGL(Proto, params) {
        const origGP = Proto.prototype.getParameter;
        const newGP = function(p) {
          if (p === 3386) return new Int32Array([16384, 16384]);
          if (p in params) return params[p];
          return origGP.call(this, p);
        };
        Object.defineProperty(Proto.prototype, 'getParameter', {
          value: newGP, writable: true, configurable: true, enumerable: true
        });
        _nativeFnNames.set(newGP, 'getParameter');

        const origGSE = Proto.prototype.getSupportedExtensions;
        const newGSE = function() {
          const exts = origGSE.call(this) || [];
          const set = new Set(exts);
          _extraExts.forEach(e => set.add(e));
          return [...set];
        };
        Object.defineProperty(Proto.prototype, 'getSupportedExtensions', {
          value: newGSE, writable: true, configurable: true, enumerable: true
        });
        _nativeFnNames.set(newGSE, 'getSupportedExtensions');

        const origGE = Proto.prototype.getExtension;
        const newGE = function(name) {
          const ext = origGE.call(this, name);
          if (!ext && name === 'EXT_texture_filter_anisotropic') {
            return { TEXTURE_MAX_ANISOTROPY_EXT: 34046, MAX_TEXTURE_MAX_ANISOTROPY_EXT: 34047 };
          }
          return ext;
        };
        Object.defineProperty(Proto.prototype, 'getExtension', {
          value: newGE, writable: true, configurable: true, enumerable: true
        });
        _nativeFnNames.set(newGE, 'getExtension');
      }

      const _wgl2AllParams = Object.assign({}, _wglParams, _wgl2Extras);
      _patchWebGL(WebGLRenderingContext, _wglParams);
      if (typeof WebGL2RenderingContext !== 'undefined') {
        _patchWebGL(WebGL2RenderingContext, _wgl2AllParams);
      }

      // --- Patch Web Workers (spoof WebGL + UAData in worker scope) ---
      // Workers run in a separate global; init-script patches don't reach them.
      // Intercept Worker constructor to prepend spoof code into worker scripts.
      const _workerPatch = `
        (function() {
          if (typeof WebGLRenderingContext !== 'undefined') {
            var params = {37445:'Intel Inc.',37446:'Intel Iris OpenGL Engine',7936:'WebKit',7937:'WebKit WebGL',3379:16384,34076:16384,34024:16384,36183:8};
            function patchGL(P) {
              var orig = P.prototype.getParameter;
              P.prototype.getParameter = function(p) {
                if (p === 3386) return new Int32Array([16384, 16384]);
                if (p in params) return params[p];
                return orig.call(this, p);
              };
            }
            patchGL(WebGLRenderingContext);
            if (typeof WebGL2RenderingContext !== 'undefined') patchGL(WebGL2RenderingContext);
          }
          if (typeof NavigatorUAData !== 'undefined') {
            var origGetHigh = NavigatorUAData.prototype.getHighEntropyValues;
            Object.defineProperty(NavigatorUAData.prototype, 'getHighEntropyValues', {
              value: async function(hints) {
                var values = await origGetHigh.call(this, hints);
                values.architecture = '${uaArch}';
                return values;
              },
              writable: true,
              configurable: true
            });
          }
        })();\n`;
      const _origWorker = window.Worker;
      const _origBlob = window.Blob;
      window.Worker = function(url, opts) {
        try {
          // Handle Blob URLs — read the blob content, prepend patch
          if (typeof url === 'string' && url.startsWith('blob:')) {
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url, false);
            xhr.send();
            if (xhr.status === 200) {
              const blob = new _origBlob([_workerPatch + xhr.responseText], {type: 'application/javascript'});
              return new _origWorker(URL.createObjectURL(blob), opts);
            }
          }
          // Handle regular URLs — fetch script, prepend patch
          if (typeof url === 'string' || (url instanceof URL)) {
            const urlStr = url instanceof URL ? url.href : url;
            const xhr = new XMLHttpRequest();
            xhr.open('GET', urlStr, false);
            xhr.send();
            if (xhr.status === 200) {
              const blob = new _origBlob([_workerPatch + xhr.responseText], {type: 'application/javascript'});
              return new _origWorker(URL.createObjectURL(blob), opts);
            }
          }
        } catch(e) {}
        return new _origWorker(url, opts);
      };
      window.Worker.prototype = _origWorker.prototype;
      _nativeFnNames.set(window.Worker, 'Worker');

      // --- Patch SharedWorker (same interception as Worker) ---
      // When ServiceWorkers are blocked, detection scripts fall back to SharedWorker.
      // Intercept SharedWorker constructor to inject the same spoof code.
      if (typeof SharedWorker !== 'undefined') {
        const _origSharedWorker = window.SharedWorker;
        window.SharedWorker = function(url, opts) {
          try {
            if (typeof url === 'string' && url.startsWith('blob:')) {
              const xhr = new XMLHttpRequest();
              xhr.open('GET', url, false);
              xhr.send();
              if (xhr.status === 200) {
                const blob = new _origBlob([_workerPatch + xhr.responseText], {type: 'application/javascript'});
                return new _origSharedWorker(URL.createObjectURL(blob), opts);
              }
            }
            if (typeof url === 'string' || (url instanceof URL)) {
              const urlStr = url instanceof URL ? url.href : url;
              const xhr = new XMLHttpRequest();
              xhr.open('GET', urlStr, false);
              xhr.send();
              if (xhr.status === 200) {
                const blob = new _origBlob([_workerPatch + xhr.responseText], {type: 'application/javascript'});
                return new _origSharedWorker(URL.createObjectURL(blob), opts);
              }
            }
          } catch(e) {}
          return new _origSharedWorker(url, opts);
        };
        window.SharedWorker.prototype = _origSharedWorker.prototype;
        _nativeFnNames.set(window.SharedWorker, 'SharedWorker');
      }

      // --- Patch document.createElement to catch unappended iframes ---
      // CreepJS creates iframes via createElement('iframe') and accesses
      // contentWindow WITHOUT appending to DOM. Our appendChild hook never fires.
      // Override contentWindow getter on each new iframe to auto-patch its window.
      const _origCreateElement = document.createElement.bind(document);
      document.createElement = function(tag, opts) {
        const el = _origCreateElement(tag, opts);
        if (tag.toLowerCase() === 'iframe') {
          const _origDesc = Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype, 'contentWindow');
          if (_origDesc && _origDesc.get) {
            const _origGet = _origDesc.get;
            Object.defineProperty(el, 'contentWindow', {
              get: function() {
                const w = _origGet.call(this);
                if (w) _patchIframeWindow(w);
                return w;
              },
              configurable: true
            });
          }
        }
        return el;
      };
      _nativeFnNames.set(document.createElement, 'createElement');

      // --- Patch iframes recursively (CreepJS uses nested "phantom" iframes) ---
      // CreepJS creates hidden iframes to access unpolluted prototypes.
      // Intercept appendChild/append to patch WebGL in each iframe window.
      function _patchIframeWindow(iWin) {
        try {
          if (!iWin || !iWin.WebGLRenderingContext) return;
          if (iWin.__wglPatched) return;
          iWin.__wglPatched = true;
          _patchWebGL(iWin.WebGLRenderingContext, _wglParams);
          if (iWin.WebGL2RenderingContext) _patchWebGL(iWin.WebGL2RenderingContext, _wgl2AllParams);
          // Recursively hook appendChild in iframe for nested iframes
          _hookAppendChild(iWin);
        } catch(e) {}
      }
      function _scanForIframes(node) {
        if (!node) return;
        const tag = node.tagName;
        if (tag === 'IFRAME') {
          try { _patchIframeWindow(node.contentWindow); } catch(e) {}
        }
        if (node.querySelectorAll) {
          try {
            node.querySelectorAll('iframe').forEach(function(iframe) {
              try { _patchIframeWindow(iframe.contentWindow); } catch(e) {}
            });
          } catch(e) {}
        }
      }
      function _collectIframes(node) {
        const iframes = [];
        if (!node) return iframes;
        if (node.tagName === 'IFRAME') iframes.push(node);
        if (node.querySelectorAll) {
          try { node.querySelectorAll('iframe').forEach(function(f) { iframes.push(f); }); } catch(e) {}
        }
        return iframes;
      }
      function _hookAppendChild(win) {
        try {
          const Proto = win.Node.prototype;
          const origAC = Proto.appendChild;
          Proto.appendChild = function(node) {
            // Collect iframes BEFORE append (DocumentFragment empties after)
            const iframes = _collectIframes(node);
            const result = origAC.call(this, node);
            // After append, contentWindow is available
            iframes.forEach(function(f) { try { _patchIframeWindow(f.contentWindow); } catch(e) {} });
            return result;
          };
          _nativeFnNames.set(Proto.appendChild, 'appendChild');
          // Also hook insertBefore
          const origIB = Proto.insertBefore;
          Proto.insertBefore = function(node, ref) {
            const iframes = _collectIframes(node);
            const result = origIB.call(this, node, ref);
            iframes.forEach(function(f) { try { _patchIframeWindow(f.contentWindow); } catch(e) {} });
            return result;
          };
          _nativeFnNames.set(Proto.insertBefore, 'insertBefore');
        } catch(e) {}
      }
      _hookAppendChild(window);
      window.__wglPatched = true;

      // --- Screen, viewport, and window dimension spoofs ---
      // Ensures consistent dimensions even if Xvfb resolution changes.
      // With X11/Xvfb at 1920x1080 these match reality but act as safety net.

      // Screen prototype
      const screenDims = { width: 1920, height: 1080, availWidth: 1920, availHeight: 1045 };
      for (const [prop, val] of Object.entries(screenDims)) {
        Object.defineProperty(Screen.prototype, prop, {
          get: () => val, configurable: true
        });
      }
      for (const prop of ['colorDepth', 'pixelDepth']) {
        Object.defineProperty(Screen.prototype, prop, {
          get: () => 24, configurable: true
        });
      }

      // Window dimensions — realistic maximized Chrome on 1920x1080
      // outerWidth > innerWidth is normal (scrollbar), outerHeight > innerHeight (chrome UI)
      const vpDims = {
        outerWidth: 1920, outerHeight: 1040,
        innerWidth: 1903, innerHeight: 969,
        screenX: 0, screenY: 0, screenLeft: 0, screenTop: 0
      };
      for (const [prop, val] of Object.entries(vpDims)) {
        Object.defineProperty(window, prop, {
          get: () => val, configurable: true
        });
      }

      // VisualViewport — matches innerWidth/innerHeight
      if (window.visualViewport) {
        for (const [prop, val] of Object.entries({
          width: 1903, height: 969,
          offsetLeft: 0, offsetTop: 0,
          pageLeft: 0, pageTop: 0, scale: 1
        })) {
          Object.defineProperty(window.visualViewport, prop, {
            get: () => val, configurable: true
          });
        }
      }

      // ScreenOrientation — 1920x1080 = landscape
      if (screen.orientation) {
        Object.defineProperty(screen.orientation, 'type', {
          get: () => 'landscape-primary', configurable: true
        });
        Object.defineProperty(screen.orientation, 'angle', {
          get: () => 0, configurable: true
        });
      }

      // matchMedia — proxy dimension queries to match our spoofed viewport.
      // CSS @media is compositor-side (ozone's real screen), but matchMedia
      // is JS-side. We override to be consistent with our viewport spoofs.
      const _origMM = window.matchMedia;
      const _vw = 1903, _vh = 969, _dw = 1920, _dh = 1080;
      window.matchMedia = function(q) {
        const r = _origMM.call(window, q);
        // Only intercept dimension queries
        if (!/(?:width|height)/.test(q)) return r;
        // Evaluate query against our dimensions
        let m = true;
        q.replace(/\(\s*(min-|max-)?(device-)?(width|height)\s*:\s*(\d+)/g,
          (_, prefix, device, dim, val) => {
            const v = parseInt(val);
            const ref = device
              ? (dim === 'width' ? _dw : _dh)
              : (dim === 'width' ? _vw : _vh);
            if (prefix === 'min-') m = m && ref >= v;
            else if (prefix === 'max-') m = m && ref <= v;
            else m = m && ref === v;
          });
        return new Proxy(r, {
          get(t, p) {
            if (p === 'matches') return m;
            const v = t[p]; return typeof v === 'function' ? v.bind(t) : v;
          }
        });
      };

      // Register remaining spoofed functions for toString
      if (navigator.share) _nativeFnNames.set(navigator.share, 'share');
      if (navigator.canShare) _nativeFnNames.set(navigator.canShare, 'canShare');
      if (navigator.mediaDevices && navigator.mediaDevices.enumerateDevices) {
        _nativeFnNames.set(navigator.mediaDevices.enumerateDevices, 'enumerateDevices');
      }
      if (window.navigator.permissions.query) {
        _nativeFnNames.set(window.navigator.permissions.query, 'query');
      }
      if (window.matchMedia) _nativeFnNames.set(window.matchMedia, 'matchMedia');

      // --- Notification API (some detectors check permission state) ---
      if (typeof Notification !== 'undefined') {
        Object.defineProperty(Notification, 'permission', {
          get: () => 'default', configurable: true
        });
      }

      // --- Fix hasKnownBgColor: headless returns rgb(255,0,0) for CSS ActiveText ---
      const _origGetCS = window.getComputedStyle;
      window.getComputedStyle = function(el, pseudo) {
        const result = _origGetCS.call(window, el, pseudo);
        if (el && el.getAttribute && el.getAttribute('style')?.includes('ActiveText')) {
          return new Proxy(result, {
            get(target, prop) {
              if (prop === 'backgroundColor') return 'rgb(0, 102, 204)';
              const v = target[prop];
              return typeof v === 'function' ? v.bind(target) : v;
            }
          });
        }
        return result;
      };
      _nativeFnNames.set(window.getComputedStyle, 'getComputedStyle');

      // prefers-color-scheme: no longer overridden.
      // Under X11/Xvfb the compositor reports light mode consistently.
      // Previously forced dark in matchMedia causing mediaConsistent: false
      // (CSS @media hash != matchMedia hash). Removing fixes the mismatch.

      // --- Fix noContentIndex: stub ContentIndex class ---
      if (!('ContentIndex' in window)) {
        window.ContentIndex = function ContentIndex() {};
        _nativeFnNames.set(window.ContentIndex, 'ContentIndex');
      }

      // --- Fix noContactsManager: stub ContactsManager class ---
      if (!('ContactsManager' in window)) {
        window.ContactsManager = function ContactsManager() {};
        _nativeFnNames.set(window.ContactsManager, 'ContactsManager');
      }

      // --- Fix noDownlinkMax: mock NetworkInformation.downlinkMax ---
      if (navigator.connection) {
        Object.defineProperty(navigator.connection, 'downlinkMax', {
          get: () => Infinity,
          configurable: true
        });
      }
    '';
  };
in
{
  # LD_LIBRARY_PATH for non-nix binaries (Chromium, Electron, downloaded tools).
  # 2 layers:
  #   Layer 1: 06-nix-ldpath.sh entrypoint fragment — sources full closure path at container start.
  #            Inherited by all services (50-gui.sh), fluxbox apps, xrdp sessions.
  #   Layer 2: zsh initContent — sources same file for interactive shells (docker exec).
  #   Fallback: patchright-mcp-cell wrapper — static runtimeLibPath for non-entrypoint contexts.
  #
  # The activation script (generateNixLdPath) scans the full profile closure at
  # home-manager switch time and writes /opt/devcell/.nix-ld-library-path into the image.
  # No circular dependency: the scan runs at activation time (after profile is built),
  # not at evaluation time.

  # Activation script: scan the profile closure for lib/ dirs containing .so files.
  # Output: /opt/devcell/.nix-ld-library-path (baked into image, not on bind mount).
  #
  # Uses config.home.path (the NEW profile's nix store path) instead of
  # config.home.profileDirectory (a symlink that may still point to the old
  # generation when this script runs). This avoids DAG ordering issues —
  # we can safely run after "writeBoundary" since the store path is resolved
  # at nix eval time, not via the runtime symlink.
  #
  # CRITICAL: exclude glibc from the path. Nix's glibc version differs from the system
  # (Debian) glibc. Including it causes system binaries (tr, grep, wc, etc.) to load
  # nix's libc.so.6 via LD_LIBRARY_PATH → symbol errors → crashes.
  home.activation.generateNixLdPath = lib.hm.dag.entryAfter ["writeBoundary"] ''
    _ldPaths=""
    for _pkg in $(${pkgs.nix}/bin/nix-store -qR "${config.home.path}"); do
      case "$_pkg" in *-glibc-*) continue ;; esac
      if [ -d "$_pkg/lib" ] && ls "$_pkg/lib/"*.so* >/dev/null 2>/dev/null; then
        _ldPaths="$_ldPaths''${_ldPaths:+:}$_pkg/lib"
      fi
    done
    echo "$_ldPaths" > "$HOME/.nix-ld-library-path"

    # Stable symlink for mesa DRI drivers — avoids hardcoded nix store hash in 50-gui.sh.
    # Without this, LIBGL_DRIVERS_PATH becomes stale after mesa version changes.
    ln -sfT "${pkgs.mesa}/lib/dri" "$HOME/.mesa-dri"
  '';

  # Source the auto-generated path at shell init for interactive shells (docker exec).
  # These don't inherit from the entrypoint, so they need their own export.
  programs.zsh.initContent = lib.mkAfter ''
    if [ -f "/opt/devcell/.nix-ld-library-path" ]; then
      export LD_LIBRARY_PATH="$(cat /opt/devcell/.nix-ld-library-path)''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    fi
  '';

  # Contribute patchright MCP server to the system-level managed-mcp.json.
  # Patchright = stealth Playwright fork — patches CDP Runtime.enable, adds
  # playwright-extra + puppeteer-extra-plugin-stealth (triple stealth stack).
  # \${VAR} in string values → literal ${VAR} in JSON → Claude Code expands at runtime.
  devcell.managedMcp.servers.playwright = {
    command = "patchright-mcp-cell";
    args = [
      "--browser" "chromium"
      # No --config or --init-script here: the wrapper auto-discovers them
      # from share/patchright/ in the nix profile, which always resolves to
      # the latest generation. This avoids nix store hash pinning in MCP args.
    ];
  };

  home.packages = with pkgs; [
    # Audio — PulseAudio with null sink for headless audio (Chromium AudioContext)
    pulseaudio # (use: pulseaudio --start --exit-idle-time=-1)

    # VNC/RDP server stack — used by entrypoint.sh when DEVCELL_GUI_ENABLED=true
    x11vnc # VNC server for X11
    xrdp   # RDP server — gateway to VNC session (entrypoint starts on port 3389)
    freerdp # RDP client (use: xfreerdp /v:host:3389 /u:user /cert:ignore)
    xorg.xorgserver # X.Org server; provides Xvfb virtual framebuffer

    # X11 display utilities
    xorg.xrandr # display configuration (from x11-apps)
    xorg.xset # X server settings utility
    xorg.xsetroot # solid color / background setter
    xorg.xrdb     # X resource database — loads .Xresources (xterm colors, fonts)

    # Background image setter — sets wallpaper before/after fluxbox starts
    feh

    # Clipboard utilities — used by entrypoint.sh clipboard sync daemon
    xclip # read/write X11 selections; used in PRIMARY↔CLIPBOARD sync loop

    # Screenshot capture — used by tests to verify desktop renders
    imagemagick # provides `import` CLI for X11 screen capture

    # X11 automation — simulate keyboard/mouse input, query windows
    xdotool # (use: xdotool key ctrl+c, xdotool search --name "Firefox")

    # Terminal emulator — launched from fluxbox menu
    xterm

    # X11 client libraries
    xorg.libX11
    xorg.libXcursor
    xorg.libxkbfile
    xorg.libXrandr

    # Graphics / rendering libraries
    cairo # 2D vector graphics (libcairo2)
    fontconfig # font configuration (libfontconfig)
    freetype # font rendering (libfreetype6)
    libGL # OpenGL (libegl1-mesa / libgl1-mesa)
    mesa  # Mesa 3D — provides llvmpipe software rasterizer for GLX on Xvfb
    glew # OpenGL extension library (libglew2.2)
    libGLU # OpenGL utility library (libglu1-mesa)
    libtiff # TIFF image library (libtiff5)

    # GTK 3 — required by many GUI apps and dialogs
    gtk3

    # wxWidgets GUI toolkit (libwxgtk3.2-1, libwxgtk-webview3.2-1)
    wxGTK32 # wxWidgets 3.2.x; attribute = wxGTK32, pname = "wxwidgets"

    # Fonts — required for Chromium and other GUI apps.
    # A real desktop has 50+ fonts. Headless environments with < 10 detectable fonts
    # are flagged by CreepJS and headless-detector. These provide broad coverage.

    # ── Nerd Fonts (dev monospace with icons) ──────────────────────────────
    nerd-fonts.jetbrains-mono  # monospace font — xterm and kitty terminal
    nerd-fonts.fira-code       # popular ligature font
    nerd-fonts.hack            # clean monospace
    nerd-fonts.meslo-lg        # macOS Terminal default derivative
    nerd-fonts.caskaydia-cove  # Cascadia Code Nerd Font
    nerd-fonts.sauce-code-pro  # Source Code Pro Nerd Font
    nerd-fonts.ubuntu-mono     # Ubuntu monospace
    nerd-fonts.roboto-mono     # Google monospace
    nerd-fonts.iosevka         # narrow monospace
    nerd-fonts.victor-mono     # cursive italic monospace
    nerd-fonts.inconsolata     # classic monospace (Google Fonts)
    nerd-fonts.droid-sans-mono # Android-era monospace
    nerd-fonts.overpass        # Red Hat inspired monospace
    nerd-fonts.go-mono         # Go programming font
    nerd-fonts.anonymice       # Anonymous Pro — clean coding font
    nerd-fonts.fantasque-sans-mono # whimsical dev font
    nerd-fonts.blex-mono       # IBM Plex Mono Nerd Font
    nerd-fonts.commit-mono     # coding font with smart kerning
    nerd-fonts.geist-mono      # Vercel's monospace font
    nerd-fonts.monaspace        # GitHub's monospace font family

    # ── Core web fonts (Arial, Times, Verdana, Georgia, etc.) ──────────────
    corefonts              # MS core web fonts (Arial, Times New Roman, Verdana, Georgia, etc.)
    noto-fonts-cjk-sans    # CJK (Chinese/Japanese/Korean) — common on real desktops

    # ── System / UI fonts (common on real desktops) ────────────────────────
    noto-fonts             # comprehensive Unicode (Noto Sans, Noto Serif)
    noto-fonts-color-emoji # color emoji — real browsers have these
    dejavu_fonts           # DejaVu Sans/Serif/Mono — Linux default
    liberation_ttf         # Liberation Sans/Serif/Mono — metric-compatible with Arial/Times/Courier
    roboto                 # Google's Android/Material UI font
    ubuntu-sans            # Ubuntu's system font family
    lato                   # popular Google Font — clean humanist sans
    open-sans              # widely used Google Font
    source-sans            # Adobe Source Sans — professional sans-serif
    source-serif           # Adobe Source Serif — matching serif
    ibm-plex              # IBM Plex Sans/Serif/Mono — modern corporate
    inter                  # geometric sans — fallback UI font
    montserrat             # geometric sans — popular for headings
    raleway                # elegant thin/light sans
    work-sans              # grotesque sans — Google Fonts
    cabin                  # humanist sans with rounded terminals
    cantarell-fonts        # GNOME's default UI font
    gentium                # SIL Gentium — academic serif
    comic-neue             # Comic Neue — legible comic-style sans
    zilla-slab             # Mozilla Zilla Slab — bold display slab-serif

    # ── Developer fonts from Google Fonts ─────────────────────────────────
    fira-sans              # Mozilla Fira Sans — pairs with Fira Code
    paratype-pt-sans       # ParaType PT Sans — clean Russian/Latin sans
    atkinson-hyperlegible  # Braille Institute — max readability sans
    quicksand              # geometric rounded sans — modern UI
    dm-sans                # DeMarco DM Sans — geometric sans
    poppins                # geometric sans — popular for modern UIs
    rubik                  # Google Rubik — slightly rounded grotesque
    karla                  # grotesque sans — minimal UI font
    barlow                 # grotesk sans — inspired by California plates
    lexend                 # readability-optimized sans — Google Fonts
    fraunces               # variable old-style serif — Google Fonts

    # Patchright MCP wrapper — sets per-app user-data-dir and forwards secrets
    # from $USER_WORKING_DIR/.env to patchright-mcp via --secrets.
    # Key names are read from .env; resolved values come from the container env
    # (injected by docker compose env_file or op run before container start).
    # Claude sees only key names, never values.
    # Bundle wrapper + config + init-script in one derivation so
    # readlink -f bin/patchright-mcp-cell → ../share/patchright/ always works.
    # When nix rebuilds, the whole derivation gets a new hash, and PATH
    # (via the profile symlink chain) resolves to the latest version.
    # No hardcoded nix store hashes leak into MCP args.
    (let
      wrapperScript = pkgs.writeShellScript "patchright-mcp-cell-inner" ''
        export LD_LIBRARY_PATH="${runtimeLibPath}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
        # Mesa Lavapipe — software Vulkan ICD for WebGL via ANGLE→Vulkan→lvp
        export VK_ICD_FILENAMES="${pkgs.mesa.drivers}/share/vulkan/icd.d/lvp_icd.${pkgs.stdenv.hostPlatform.uname.processor}.json"

        # Always use config and init-script from co-located share/ dir.
        # Strip any stale --config/--init-script from caller args (e.g. Claude Code
        # caching old nix store hashes) so the bundled versions always win.
        _SELF="$(readlink -f "$0")"
        _SHARE="$(dirname "$(dirname "$_SELF")")/share/patchright"
        _CLEAN_ARGS=()
        _skip=false
        for _a in "$@"; do
          if $_skip; then _skip=false; continue; fi
          case "$_a" in
            --config|--init-script) _skip=true; continue ;;
          esac
          _CLEAN_ARGS+=("$_a")
        done
        set -- "''${_CLEAN_ARGS[@]}"
        _EXTRA_ARGS=()
        [ -f "$_SHARE/config.json" ] && _EXTRA_ARGS+=(--config "$_SHARE/config.json")
        [ -f "$_SHARE/stealth-init.js" ] && _EXTRA_ARGS+=(--init-script "$_SHARE/stealth-init.js")

        SECRETS_FILE=$(mktemp /tmp/pw-secrets-XXXXXX.env)
        trap 'rm -f "$SECRETS_FILE"' EXIT

        _ENV_FILE="''${USER_WORKING_DIR:-}/.env"
        if [ -f "$_ENV_FILE" ]; then
          while IFS= read -r _line || [ -n "$_line" ]; do
            [[ -z "$_line" || "$_line" == '#'* ]] && continue
            _key="''${_line%%=*}"
            _key="''${_key#export }"
            [ -z "$_key" ] && continue
            if _val=$(printenv "$_key" 2>/dev/null); then
              printf '%s=%s\n' "$_key" "$_val"
            fi
          done < "$_ENV_FILE" >> "$SECRETS_FILE"
        fi

        USER_DATA_DIR="''${PLAYWRIGHT_MCP_USER_DATA_DIR:-$HOME/.playwright-''${APP_NAME:-cell}}"
        mcp-server-patchright --no-sandbox --user-data-dir "$USER_DATA_DIR" --secrets "$SECRETS_FILE" "''${_EXTRA_ARGS[@]}" "$@"
      '';
    in pkgs.runCommandLocal "patchright-mcp-cell" {} ''
      mkdir -p $out/bin $out/share/patchright
      cp ${wrapperScript} $out/bin/patchright-mcp-cell
      chmod +x $out/bin/patchright-mcp-cell
      cp ${patchrightConfig} $out/share/patchright/config.json
      cp ${stealthInitScript} $out/share/patchright/stealth-init.js
    '')
  ];

  # Enable user fontconfig so Chromium and X11 apps find the nix-installed fonts.
  fonts.fontconfig.enable = true;

  # ── Fluxbox configuration ──────────────────────────────────────────────────
  # Declared via the home-manager fluxbox module — generates ~/.fluxbox/{init,menu,...}.
  # homeDirectory is /opt/devcell so ~/.fluxbox is at /opt/devcell/.fluxbox (stable).
  # entrypoint.sh launches fluxbox with: fluxbox -rc /opt/devcell/.fluxbox/init

  xsession.windowManager.fluxbox = {
    enable = true;

    inherit init;

    # Full keybindings. home-manager replaces the entire default keys file,
    # so we must include useful defaults here. Scroll-to-cycle-workspaces
    # is deliberately mapped to :NOP — macOS trackpad momentum scrolling
    # floods VNC with Button4/5 events causing a "doom scroll" effect.
    keys = ''
      # Window focus and movement
      Mod1 Tab :NextWindow {groups} (workspace=[current])
      Mod1 Shift Tab :PrevWindow {groups} (workspace=[current])
      Mod1 F4 :Close
      Mod1 F9 :Minimize
      Mod1 F10 :Maximize
      Mod1 F11 :Fullscreen

      # Workspace navigation (keyboard only — scroll deliberately disabled)
      Control Mod1 Left :PrevWorkspace
      Control Mod1 Right :NextWorkspace

      # Window movement and resizing
      OnTitlebar Mouse1 :MacroCmd {Focus} {Raise} {ActivateTab}
      OnTitlebar Move1 :StartMoving
      OnTitlebar Double Mouse1 :Maximize
      OnTitlebar Mouse3 :WindowMenu
      OnWindow Mod1 Mouse1 :MacroCmd {Raise} {Focus} {StartMoving}
      OnWindow Mod1 Mouse3 :MacroCmd {Raise} {Focus} {StartResizing NearestCorner}
      OnWindowBorder Move1 :StartMoving

      # Desktop menus
      OnDesktop Mouse1 :HideMenus
      OnDesktop Mouse2 :WorkspaceMenu
      OnDesktop Mouse3 :RootMenu

      # Scroll on desktop/toolbar: NOP (prevents macOS trackpad doom scroll)
      OnDesktop Mouse4 :NOP
      OnDesktop Mouse5 :NOP
      OnToolbar Mouse4 :NOP
      OnToolbar Mouse5 :NOP
    '';

    # Chromium via the home-manager profile wrapper (includes --no-sandbox, --disable-gpu,
    # --user-data-dir etc. set in web.nix). Shell expansion resolves $USER at runtime
    # so the compat link /nix/var/nix/profiles/per-user/$USER/profile is used correctly
    # regardless of which username the container runs as.
    menu = ''
      [begin] ([*.] devcell)
        [submenu] (Applications)
          [exec] (Chromium) {sh -c 'chromium &'}
        [end]
        [exec] (Kitty) {${pkgs.kitty}/bin/kitty}
        [exec] (XTerm) {${pkgs.xterm}/bin/xterm}
        [separator]
        [exit] (Exit Fluxbox)
      [end]
    '';
  };

  # ── Kitty terminal — GPU-accelerated with software fallback ───────────
  programs.kitty = {
    enable = true;
    font = {
      name = "JetBrainsMono Nerd Font";
      size = 11;
    };
    settings = {
      # ── Colors — neobrutalist palette from theme.nix ──
      background = c.surface;
      foreground = "#e0f0ff";
      cursor = c.accent;
      cursor_text_color = c.surface;
      selection_background = "#334455";
      selection_foreground = "#ffffff";
      url_color = c.accent;
      url_style = "curly";

      # ── Window borders (kitty splits, not WM) ──
      active_border_color = c.accent;
      inactive_border_color = c.inactive;
      bell_border_color = c.close;
      window_border_width = "1px";

      # ── Window chrome ──
      window_padding_width = 8;
      hide_window_decorations = false;

      # ── Rendering — software fallback for containers without GPU ──
      linux_display_server = "x11";

      # ── Bell ──
      enable_audio_bell = false;
      visual_bell_duration = "0.15";
      visual_bell_color = c.raised;

      # ── Scrollback ──
      scrollback_lines = 10000;

      # ── Opacity ──
      dim_opacity = "0.7";
      inactive_text_alpha = "0.8";

      # ── Tab bar — powerline style matching toolbar ──
      tab_bar_edge = "bottom";
      tab_bar_style = "powerline";
      tab_powerline_style = "slanted";
      tab_bar_background = c.border;
      active_tab_background = c.accent;
      active_tab_foreground = c.border;
      active_tab_font_style = "bold";
      inactive_tab_background = c.raised;
      inactive_tab_foreground = c.inactive;
      inactive_tab_font_style = "normal";

      # ── Marks (ctrl+shift+1/2/3 to highlight patterns) ──
      mark1_background = c.accent;
      mark1_foreground = c.border;
      mark2_background = c.highlight;
      mark2_foreground = c.border;
      mark3_background = c.close;
      mark3_foreground = c.textBright;

      # ── Terminal colors (same as Xresources) ──
      color0  = c.surface;
      color1  = "#ff5555";
      color2  = c.highlight;
      color3  = "#f1fa8c";
      color4  = "#2e86c1";
      color5  = "#bd93f9";
      color6  = c.accent;
      color7  = "#bfbfbf";
      color8  = "#555577";
      color9  = "#ff6e6e";
      color10 = "#c8f346";
      color11 = "#ffffa5";
      color12 = "#5dade2";
      color13 = "#d6bcfa";
      color14 = "#48d1b5";
      color15 = c.textBright;
    };
  };

  # ── Theme file deployment ─────────────────────────────────────────────────
  # All visual assets: wallpaper, Xresources, fluxbox style + overlay, button pixmaps.
  home.file = {
    ".fluxbox/wallpaper.png".source = wallpaper;
    ".Xresources".text = xresources;
    ".fluxbox/styles/devcell-ocean/theme.cfg".text = cfg;
    ".fluxbox/overlay".text = cfg;
    ".fluxbox/apps".text = ''
      [app] (name=.*)
        [Tab] {no}
        [Deco] {NORMAL}
      [end]
    '';
    # ── Entrypoint fragment: LD_LIBRARY_PATH from full nix closure ──────────
    # Sourced by entrypoint.sh BEFORE 50-gui.sh. All services inherit this export.
    ".config/devcell/entrypoint.d/06-nix-ldpath.sh" = {
      executable = true;
      source = ../fragments/06-nix-ldpath.sh;
    };

    # ── Entrypoint fragment: GUI service startup ────────────────────────────
    # Sourced by entrypoint.sh from /etc/devcell/entrypoint.d/ at container start.
    ".config/devcell/entrypoint.d/50-gui.sh" = {
      executable = true;
      source = ../fragments/50-gui.sh;
    };
  } // pixmaps;
}
