# hosts/linux/home.nix — home-manager config for the vagrant user on the Linux VM.
# Essential vagrant modules (shell, LLM tools, mise) are always included.
# Stack + extra modules are controlled by ./stack.nix, which is regenerated
# from .devcell.toml by `cell claude --engine=vagrant` / `cell build --engine=vagrant`.
{ mcp-nixos, ... }: {
  imports = [
    ./stack.nix            # Generated by cell — stack + extra modules from .devcell.toml
    ../../modules/shell.nix
    ../../modules/llm
    ../../modules/mise.nix
  ];

  home.username = "vagrant";
  home.homeDirectory = "/home/vagrant";
  home.stateVersion = "25.11";
}
